### PR TITLE
Typescript migration

### PR DESCRIPTION
**Pull request by sdstolworthy**

### CODE REVIEW

**Comment by sdstolworthy** [comment]
@jacobsee @cognizen @lallmon In the call we briefly talked about a migration to typescript while the project is still small. It was a pretty quick fix, so I just went ahead and did it. If we don't want to go the TS route, feel free to close or comment.

**Comment by sdstolworthy** [comment]
@lallmon I don't know if it's strictly necessary. Just in my personal experience the small time it takes to define interfaces and classes pales in comparison to the time it takes to track data flowing from component to component (even with proptypes/flow). That being said, this is still a small project, so it may be overkill. Do you want to hold off?

**Comment by mcanoy** [comment]
I’ll just add that will this is currently a small project the expectation is that this will grow significantly especially if this project gains traction. The long term feature list is quite long.

**Comment by lallmon** [comment]
@mcanoy Not exactly sure if that comment is pro TS or not. 😆

**Pull request merged**
